language: node_js
node_js:
  - '4'
  - '6'
before_script:
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
sudo: false
